### ISSUE TITLE
Cannot compile on Ubuntu 12.04

### ISSUE THREAD

**Issue by coolwanglu** [fontforge/fontforge#143]
./.libs/libfontforgeexe.so: undefined reference to `UndoRedoLimitToLoad'
./.libs/libfontforgeexe.so: undefined reference to`UndoRedoLimitToSave'
./.libs/libfontforgeexe.so: undefined reference to `UndoesFreeButRetainFirstN'
