### PR TITLE
contrib: Remove unneeded header includes

### LINKED ISSUE #3155: contrib/fonttools do not compile
This was reported to Homebrew in [fontforge fails to install. Can't find "mem.h"](https://github.com/Homebrew/homebrew-core/issues/18398). The build fails with
```
==> make
Last 15 lines from /Users/tyler.abair/Library/Logs/Homebrew/fontforge/03.make:
         ^~~~~~~
findtable.c:5:10: fatal error: 'mem.h' file not found
#include "mem.h"
         ^~~~~~~
1 error generated.
make: *** [findtable.o] Error 1
1 error generated.
make: *** [pcl2ttf.o] Error 1
dewoff.c:7:10: fatal error: 'mem.h' file not found
#include "mem.h"
         ^~~~~~~
1 error generated.
make: *** [dewoff.o] Error 1
1 error generated.
make: *** [showttf.o] Error 1
```

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
fontforge-dist-20170731 on macOS 10.11
- [x] The behavior you expect to see, and the actual behavior
successful build not failed build
- [x] Steps to reproduce the behavior
```
cd contrib/fonttools
make
```
- [x] \(optional) Possible solution/fix/workaround

don't pass `--with-extra-tools` to `brew install fontforge`

### PR DESCRIPTION
**Pull request by jtanx**
These were introduced with 0b8be8d93f5bd68473ed739b63a3c8bdf14d23e4 and
ae657bca203ecdac7a508aec0e43dec6b0b31883, likely with a script.

They aren't actually needed, because all the required definitions
are redefined/copied into the contrib files.

Fixes #3155

### CODE REVIEW

**Comment by gioele** [comment]
Thnks @jtanx, it is nice to have Travis test the contrib tools as well
