### PR TITLE
osx: Replace require_noerr with __Require_noErr

### LINKED ISSUE #3164: fontforge uses obsolete require_noerr macro, causes build failure on macOS High Sierrra (10.13)
fontforge 20120731 fails to build on macOS High Sierra (10.13):

```
startui.c:771:5: warning: implicit declaration of function 'require_noerr' is invalid in C99 [-Wimplicit-function-declaration]
    require_noerr(err, CantInstallAppleEventHandler);
    ^
```

```
startui.c:771:24: error: use of undeclared identifier 'CantInstallAppleEventHandler'
    require_noerr(err, CantInstallAppleEventHandler);
                       ^
```

As it says in /usr/include/AssertMacros.h on High Sierra:

```
/*
 *      For time immemorial, Mac OS X has defined version of most of these macros without the __ prefix, which
 *      could collide with similarly named functions or macros in user code, including new functionality in
 *      Boost and the C++ standard library.
 *
 *  macOS High Sierra and iOS 11 will now require that clients move to the new macros as defined above.
 *
 *  If you would like to enable the macros for use within your own project, you can define the
 *  __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES macro via an Xcode Build Configuration.
 *  See "Add a build configuration (xcconfig) file" in Xcode Help. 
 *
 *  To aid users of these macros in converting their sources, the following tops script will convert usages
 *  of the old macros into the new equivalents.  To do so, in Terminal go into the directory containing the
 *  sources to be converted and run this command.
 *
    find . -name '*.[c|cc|cp|cpp|m|mm|h]' -print0 |  xargs -0 tops -verbose \
      replace "check(<b args>)" with "__Check(<args>)" \
      replace "check_noerr(<b args>)" with "__Check_noErr(<args>)" \
      replace "check_noerr_string(<b args>)" with "__Check_noErr_String(<args>)" \
      replace "check_string(<b args>)" with "__Check_String(<args>)" \
      replace "require(<b args>)" with "__Require(<args>)" \
      replace "require_action(<b args>)" with "__Require_Action(<args>)" \
      replace "require_action_string(<b args>)" with "__Require_Action_String(<args>)" \
      replace "require_noerr(<b args>)" with "__Require_noErr(<args>)" \
      replace "require_noerr_action(<b args>)" with "__Require_noErr_Action(<args>)" \
      replace "require_noerr_action_string(<b args>)" with "__Require_noErr_Action_String(<args>)" \
      replace "require_noerr_string(<b args>)" with "__Require_noErr_String(<args>)" \
      replace "require_string(<b args>)" with "__Require_String(<args>)" \
      replace "verify(<b args>)" with "__Verify(<args>)" \
      replace "verify_action(<b args>)" with "__Verify_Action(<args>)" \
      replace "verify_noerr(<b args>)" with "__Verify_noErr(<args>)" \
      replace "verify_noerr_action(<b args>)" with "__Verify_noErr_Action(<args>)" \
      replace "verify_noerr_string(<b args>)" with "__Verify_noErr_String(<args>)" \
      replace "verify_string(<b args>)" with "__Verify_String(<args>)" \
      replace "ncheck(<b args>)" with "__nCheck(<args>)" \
      replace "ncheck_string(<b args>)" with "__nCheck_String(<args>)" \
      replace "nrequire(<b args>)" with "__nRequire(<args>)" \
      replace "nrequire_action(<b args>)" with "__nRequire_Action(<args>)" \
      replace "nrequire_action_quiet(<b args>)" with "__nRequire_Action_Quiet(<args>)" \
      replace "nrequire_action_string(<b args>)" with "__nRequire_Action_String(<args>)" \
      replace "nrequire_quiet(<b args>)" with "__nRequire_Quiet(<args>)" \
      replace "nrequire_string(<b args>)" with "__nRequire_String(<args>)" \
      replace "nverify(<b args>)" with "__nVerify(<args>)" \
      replace "nverify_string(<b args>)" with "__nVerify_String(<args>)" \
      replace "require_action_quiet(<b args>)" with "__Require_Action_Quiet(<args>)" \
      replace "require_noerr_action_quiet(<b args>)" with "__Require_noErr_Action_Quiet(<args>)" \
      replace "require_noerr_quiet(<b args>)" with "__Require_noErr_Quiet(<args>)" \
      replace "require_quiet(<b args>)" with "__Require_Quiet(<args>)" \
      replace "check_compile_time(<b args>)" with "__Check_Compile_Time(<args>)" \
      replace "debug_string(<b args>)" with "__Debug_String(<args>)"
 *
 */
```

The [MacPorts project's bug report about this issue](https://trac.macports.org/ticket/54960) has a build log, if you need that.

I realize 20120731 is an old version (and we'd love to [update to a later version](https://trac.macports.org/ticket/43844)) but I looked at the latest source code here on GitHub and it looks like you're still using the `require_noerr` macro, and I don't see anywhere where you're defining `__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES`.

### PR DESCRIPTION
**Pull request by jtanx**
Resolves #3164

### CODE REVIEW

**Comment by ryandesign** [comment]
Of course, merely replacing `require_noerr` with `__Require_noErr` will make fontforge incompatible with old versions of macOS that don't have the underscored version (i.e. 10.5.x and earlier).

**Comment by frank-trampe** [comment]
The binary build still happens on 10.10, so we do need to support that, but I'd also like to avoid unconditionally mapping one macro to another. Is there a macro that would tell us nicely which name mode the hosting platform implements?

**Comment by ryandesign** [comment]
> The binary build still happens on 10.10, so we do need to support that,

The underscored versions should be available from 10.6 onward, so you should be fine there.

> but I'd also like to avoid unconditionally mapping one macro to another. Is there a macro that would tell us nicely which name mode the hosting platform implements?

I'm not sure. I doubt Apple considered that anyone writing code for High Sierra might still want to support Leopard. The simplest way to continue to do so would be to keep the code as it is and define `__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES`, but Apple might remove that in a future version of macOS.

**Comment by jtanx** [comment]
Yeah, I'd say it's fine to leave it as is. Homebrew has long dropped support for Leopard, and from what I recall, our current builds wouldn't even work on Leopard anyway.
